### ISSUE TITLE
technologies to be used

### ISSUE THREAD

**Issue by 1995YogeshSharma** [WebDev-IIITH/Game-Of-Codes#1]
write down the appropriate technologies in the readme.

**Comment by 1995YogeshSharma** [comment]
@mukulhase any updates on this ?

**Comment by hharchani** [comment]
Let's decide on this so that we can start. @nisargjhaveri what say?

**Comment by pinkeshbadjatiya** [comment]
@nisargjhaveri suggested node.js
php, django, javascript, etc is what i can think of.
Since this is 1st event, we must start with what we are good it, hence my suggestion is `django`.

**Comment by 1995YogeshSharma** [comment]
i think nodejs + angularjs is a good combination

**Comment by suhasdarsi** [comment]
The question is do we need such high scalable stuff ? can we not just do it with stuff like flask or web2py

**Comment by erilyth** [comment]
@1995YogeshSharma I think using angularjs is just over sophisticating things.

**Comment by suhasdarsi** [comment]
Profile pics help @erilyth

**Comment by 1995YogeshSharma** [comment]
@erilyth if people are comfortable with angularjs it's not sophisticated.. otherwise for now we can stay with django as well..

**Comment by erilyth** [comment]
Should we poll on this?

**Comment by ParinVachhani** [comment]
Yeah I agree that we should not over-complicate things for this first portal. We have all the opportunities to  show off our skills on bigger frameworks in future for real portals

**Comment by nisargjhaveri** [comment]
Please no more polls! :P

Use `django`, since many of you are familiar with it.

Frontend, use jQuery! :P (You can use whatever you want, just no more polls!)

**Comment by erilyth** [comment]
@nisargjhaveri , +1 for jQuery + django

**Comment by suhasdarsi** [comment]
resolve this issue let's get over with this now

**Comment by hharchani** [comment]
@nisargjhaveri why no polls?

Also, What are all the options?

Node + Express + Angular + Mysql
Node + Express + Angular + Mongo (MEAN stack)
We can use React instead of Angular.

Django + jQuery
Django + some frontend framework (Raect, Ember, Backbone, Angular)

**Comment by hharchani** [comment]
And trust me, no framework is sophisticated. Using frameworks helps also at many places and it improves the code quality in general

**Comment by ParinVachhani** [comment]
Please @hharchani, let's not complicate this. I am pretty sure most of us are not confident with Node, Express, Angular, etc so let's just stick to Django for now and use something relatively simple like jQuery.

**Comment by hharchani** [comment]
Okay, let's not go with Node, if you people are pretty confident with Django.
But I'm still in favor of using a frontend framework.

**Comment by suhasdarsi** [comment]
Start off with whatever you guys intend to use I'll just pick it up I'm cool with whatever you want to use

**Comment by hharchani** [comment]
So let us finalize this. Let's go with Django + just jQuery for now. If we need some frontend framework, we'll have a discussion then and finalize.

Just remember, we need to complete it by tomorrow.

**Comment by pinkeshbadjatiya** [comment]
@hharchani that is the main reason why i suggested django :p

**Comment by hharchani** [comment]
So admins @mukulhase, @nisargjhaveri mark this issue resolve so that we proceed.

**Comment by nisargjhaveri** [comment]
Okay, Django + jQuery! (+ something for CSS maybe)
