### ISSUE TITLE
Requirement of the portal

### ISSUE THREAD

**Issue by hharchani** [WebDev-IIITH/Game-Of-Codes#2]
What are all the features needed?

**Comment by suhasdarsi** [comment]
We need to have a timer, We need to give a link to an online IDE, A buzzer

**Comment by nisargjhaveri** [comment]
https://docs.google.com/document/d/1PIUGqw-Hx0P_Pv0X0VR3A-WpuaIYPWzI78CmfQNS8Mo/edit

**Comment by 1995YogeshSharma** [comment]
we are going with django for this portal...
